### ISSUE TITLE
Toggle encryption on/off

### ISSUE THREAD

**Issue by marint94** [Hmerritt/discord-encryption#1]
You're a life saver man.
I was looking for something like this for months!
Could you make a toggle for encryption on/off instead of having to encrypt every message?

Example: I chat with my friend "Bob", so I turn on encryption and every message I text him is encrypted.

**Comment by Hmerritt** [comment]
### Thank you for the suggestion
An encryption toggle is a great idea and I would love to add this feature.
I will, however, need to have a look if it is even possible to implement using betterdiscord's current framework. If it is possible I will work to implement this feature

**Comment by Hmerritt** [comment]
### From idea to fruition
I have just added an encryption button which, when active, will encrypt all messages being sent
