### ISSUE TITLE
HEY! no realtime decryption? 

### ISSUE THREAD

**Issue by Hasplit** [Hmerritt/discord-encryption#5]
Kindof an issue but not too much more like a request

I notice that it only decrypts when a person sends a message. however im in a big server and it doesnt like to be cluttered so i was wondering if this could maybe be added?
(Edit) 
Maybe a suggestion is to make it decrypt everytime we click enter so we can manually do so? im not a js programmer so i cant really understand how you could do it but it would be nice.

**Comment by Hmerritt** [comment]
## Fixed (for now at least)

I should have fixed all problems with encrypting and decrypting.

If you are interested in why it broke to begin with it has to do with discord updating (I do not think they want people using BetterDiscord) so they change very minor things in the code e.g. 'message' to 'msg'. This seemingly pointless change is fatal to most BetterDiscord scripts as they cannot lock onto the messages. Luckily this is very easy to fix but will break again if Discord change it again in an update.
