### ISSUE TITLE
Doesn't decrypt the message

### ISSUE THREAD

**Issue by DasCanard** [hmerritt/discord-encryption#8]
its again the same problem

**Comment by evilcommand** [comment]
my friendc can see the message dycrypted but i cant not on my PC or laptop
any idea how to fix it ???

**Comment by EnKrypt** [comment]
This plugin has a few concerns: look at the other issue I've opened.
It also looks like the developer is away and hasn't been responsive.

As a solution I've created a plugin myself that is doing well. It's been tested by various members and receives regular updated. Do check it out :
https://github.com/EnKrypt/DiscordEncryption

**Comment by EnKrypt** [comment]
This plugin has a few concerns: look at the other issue I've opened in this repository.
It also looks like the developer is away and hasn't been responsive.

As a solution I've created a plugin myself that is doing well. It's been tested by various members and receives regular updates. Do check it out, hopefully that will fulfill your requirements.

https://github.com/EnKrypt/DiscordEncryption

**Comment by hmerritt** [comment]
(I know I am massively late to this one and I am deeply sorry for that)

I am re-writing this script from the ground-up; hopefully fixing this problem and many others.

**Comment by EnKrypt** [comment]
No worries at all.

I actually drew inspiration from your project and made my own version, which got a bit of attention.

https://github.com/EnKrypt/DiscordEncryption

It worked fine for a long while until the last Discord update which broke the plugin. There is currently one active issue on it preventing people from using it properly. Feel free to help me fix it, or just reuse whatever I've written in your own project however you want. Cheers mate.

**Comment by hmerritt** [comment]
Fixed in #9
